//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vesl00_4IT449_semestralka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class highscore
    {
        public string nick { get; set; }
        public int score { get; set; }
    }
}
